// Generated by `supabase gen types typescript` (via MCP) from project xgxuwimcxkpgtfkunwfe.
// Regenerate whenever the schema changes: supabase gen types typescript --linked > src/lib/db/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      appointments: {
        Row: {
          cancellation_reason: string | null
          client_id: string
          client_timezone: string | null
          created_at: string
          currency: Database["public"]["Enums"]["currency"] | null
          ends_at: string
          fee_minor: number | null
          firm_id: string
          hold_expires_at: string | null
          id: string
          invoice_id: string | null
          lawyer_id: string | null
          matter_id: string | null
          mode: Database["public"]["Enums"]["appointment_mode"]
          reference: string
          reminders_sent: string[]
          service_id: string | null
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
        }
        Insert: {
          cancellation_reason?: string | null
          client_id: string
          client_timezone?: string | null
          created_at?: string
          currency?: Database["public"]["Enums"]["currency"] | null
          ends_at: string
          fee_minor?: number | null
          firm_id: string
          hold_expires_at?: string | null
          id?: string
          invoice_id?: string | null
          lawyer_id?: string | null
          matter_id?: string | null
          mode?: Database["public"]["Enums"]["appointment_mode"]
          reference: string
          reminders_sent?: string[]
          service_id?: string | null
          starts_at: string
          status?: Database["public"]["Enums"]["appointment_status"]
        }
        Update: {
          cancellation_reason?: string | null
          client_id?: string
          client_timezone?: string | null
          created_at?: string
          currency?: Database["public"]["Enums"]["currency"] | null
          ends_at?: string
          fee_minor?: number | null
          firm_id?: string
          hold_expires_at?: string | null
          id?: string
          invoice_id?: string | null
          lawyer_id?: string | null
          matter_id?: string | null
          mode?: Database["public"]["Enums"]["appointment_mode"]
          reference?: string
          reminders_sent?: string[]
          service_id?: string | null
          starts_at?: string
          status?: Database["public"]["Enums"]["appointment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "appointments_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "partner_attribution"
            referencedColumns: ["invoice_id"]
          },
          {
            foreignKeyName: "appointments_lawyer_id_fkey"
            columns: ["lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          at: string
          entity: string
          entity_id: string | null
          firm_id: string | null
          id: number
          ip: unknown
          meta: Json
        }
        Insert: {
          action: string
          actor_id?: string | null
          at?: string
          entity: string
          entity_id?: string | null
          firm_id?: string | null
          id?: number
          ip?: unknown
          meta?: Json
        }
        Update: {
          action?: string
          actor_id?: string | null
          at?: string
          entity?: string
          entity_id?: string | null
          firm_id?: string | null
          id?: number
          ip?: unknown
          meta?: Json
        }
        Relationships: []
      }
      availability_exceptions: {
        Row: {
          end_time: string | null
          firm_id: string
          id: string
          is_available: boolean
          lawyer_id: string
          on_date: string
          reason: string | null
          start_time: string | null
        }
        Insert: {
          end_time?: string | null
          firm_id: string
          id?: string
          is_available?: boolean
          lawyer_id: string
          on_date: string
          reason?: string | null
          start_time?: string | null
        }
        Update: {
          end_time?: string | null
          firm_id?: string
          id?: string
          is_available?: boolean
          lawyer_id?: string
          on_date?: string
          reason?: string | null
          start_time?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "availability_exceptions_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "availability_exceptions_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "availability_exceptions_lawyer_id_fkey"
            columns: ["lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      availability_rules: {
        Row: {
          break_end: string | null
          break_start: string | null
          end_time: string
          firm_id: string
          id: string
          lawyer_id: string
          max_per_day: number
          slot_min: number
          start_time: string
          weekday: number
        }
        Insert: {
          break_end?: string | null
          break_start?: string | null
          end_time: string
          firm_id: string
          id?: string
          lawyer_id: string
          max_per_day?: number
          slot_min?: number
          start_time: string
          weekday: number
        }
        Update: {
          break_end?: string | null
          break_start?: string | null
          end_time?: string
          firm_id?: string
          id?: string
          lawyer_id?: string
          max_per_day?: number
          slot_min?: number
          start_time?: string
          weekday?: number
        }
        Relationships: [
          {
            foreignKeyName: "availability_rules_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "availability_rules_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "availability_rules_lawyer_id_fkey"
            columns: ["lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conflict_checks: {
        Row: {
          firm_id: string
          id: string
          matches: Json | null
          matter_id: string | null
          outcome: string | null
          query: Json | null
          reviewed_at: string | null
          reviewed_by: string | null
        }
        Insert: {
          firm_id: string
          id?: string
          matches?: Json | null
          matter_id?: string | null
          outcome?: string | null
          query?: Json | null
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
        Update: {
          firm_id?: string
          id?: string
          matches?: Json | null
          matter_id?: string | null
          outcome?: string | null
          query?: Json | null
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conflict_checks_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conflict_checks_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conflict_checks_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conflict_checks_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_records: {
        Row: {
          accepted_at: string
          firm_id: string | null
          id: string
          ip: unknown
          kind: Database["public"]["Enums"]["consent_kind"]
          user_agent: string | null
          user_id: string
          version: string
        }
        Insert: {
          accepted_at?: string
          firm_id?: string | null
          id?: string
          ip?: unknown
          kind: Database["public"]["Enums"]["consent_kind"]
          user_agent?: string | null
          user_id: string
          version: string
        }
        Update: {
          accepted_at?: string
          firm_id?: string | null
          id?: string
          ip?: unknown
          kind?: Database["public"]["Enums"]["consent_kind"]
          user_agent?: string | null
          user_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "consent_records_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consent_records_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consent_records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      consultation_internal_notes: {
        Row: {
          appointment_id: string
          body: string | null
          created_at: string
          firm_id: string
          id: string
          updated_at: string
        }
        Insert: {
          appointment_id: string
          body?: string | null
          created_at?: string
          firm_id: string
          id?: string
          updated_at?: string
        }
        Update: {
          appointment_id?: string
          body?: string | null
          created_at?: string
          firm_id?: string
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "consultation_internal_notes_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: true
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_internal_notes_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_internal_notes_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      consultation_notes: {
        Row: {
          advice_given: string | null
          appointment_id: string
          client_summary: string | null
          created_at: string
          firm_id: string
          follow_up: string | null
          id: string
          lawyer_id: string | null
          matter_id: string | null
          updated_at: string
        }
        Insert: {
          advice_given?: string | null
          appointment_id: string
          client_summary?: string | null
          created_at?: string
          firm_id: string
          follow_up?: string | null
          id?: string
          lawyer_id?: string | null
          matter_id?: string | null
          updated_at?: string
        }
        Update: {
          advice_given?: string | null
          appointment_id?: string
          client_summary?: string | null
          created_at?: string
          firm_id?: string
          follow_up?: string | null
          id?: string
          lawyer_id?: string | null
          matter_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "consultation_notes_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: true
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_notes_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_notes_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_notes_lawyer_id_fkey"
            columns: ["lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_notes_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
        ]
      }
      consultation_sessions: {
        Row: {
          appointment_id: string
          client_admitted_at: string | null
          ended_at: string | null
          events: Json
          firm_id: string
          id: string
          provider: string
          room_expires_at: string | null
          room_name: string | null
          started_at: string | null
        }
        Insert: {
          appointment_id: string
          client_admitted_at?: string | null
          ended_at?: string | null
          events?: Json
          firm_id: string
          id?: string
          provider?: string
          room_expires_at?: string | null
          room_name?: string | null
          started_at?: string | null
        }
        Update: {
          appointment_id?: string
          client_admitted_at?: string | null
          ended_at?: string | null
          events?: Json
          firm_id?: string
          id?: string
          provider?: string
          room_expires_at?: string | null
          room_name?: string | null
          started_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "consultation_sessions_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: true
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_sessions_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_sessions_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      content: {
        Row: {
          body: string | null
          firm_id: string
          id: string
          kind: Database["public"]["Enums"]["content_kind"]
          published_at: string | null
          slug: string | null
          status: string
          title: string | null
        }
        Insert: {
          body?: string | null
          firm_id: string
          id?: string
          kind: Database["public"]["Enums"]["content_kind"]
          published_at?: string | null
          slug?: string | null
          status?: string
          title?: string | null
        }
        Update: {
          body?: string | null
          firm_id?: string
          id?: string
          kind?: Database["public"]["Enums"]["content_kind"]
          published_at?: string | null
          slug?: string | null
          status?: string
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "content_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      court_events: {
        Row: {
          court_name: string | null
          firm_id: string
          id: string
          matter_id: string
          outcome_update_id: string | null
          purpose: string | null
          reminders_sent: string[]
          scheduled_at: string
        }
        Insert: {
          court_name?: string | null
          firm_id: string
          id?: string
          matter_id: string
          outcome_update_id?: string | null
          purpose?: string | null
          reminders_sent?: string[]
          scheduled_at: string
        }
        Update: {
          court_name?: string | null
          firm_id?: string
          id?: string
          matter_id?: string
          outcome_update_id?: string | null
          purpose?: string | null
          reminders_sent?: string[]
          scheduled_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "court_events_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_events_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_events_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_events_outcome_update_id_fkey"
            columns: ["outcome_update_id"]
            isOneToOne: false
            referencedRelation: "updates"
            referencedColumns: ["id"]
          },
        ]
      }
      document_versions: {
        Row: {
          checksum: string | null
          created_at: string
          document_id: string
          id: string
          mime: string | null
          size_bytes: number | null
          storage_path: string
          uploaded_by: string | null
        }
        Insert: {
          checksum?: string | null
          created_at?: string
          document_id: string
          id?: string
          mime?: string | null
          size_bytes?: number | null
          storage_path: string
          uploaded_by?: string | null
        }
        Update: {
          checksum?: string | null
          created_at?: string
          document_id?: string
          id?: string
          mime?: string | null
          size_bytes?: number | null
          storage_path?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "document_versions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_versions_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          appointment_id: string | null
          category: string | null
          client_visible: boolean
          created_at: string
          current_version_id: string | null
          deleted_at: string | null
          firm_id: string
          id: string
          matter_id: string | null
          name: string
          uploaded_by: string | null
        }
        Insert: {
          appointment_id?: string | null
          category?: string | null
          client_visible?: boolean
          created_at?: string
          current_version_id?: string | null
          deleted_at?: string | null
          firm_id: string
          id?: string
          matter_id?: string | null
          name: string
          uploaded_by?: string | null
        }
        Update: {
          appointment_id?: string | null
          category?: string | null
          client_visible?: boolean
          created_at?: string
          current_version_id?: string | null
          deleted_at?: string | null
          firm_id?: string
          id?: string
          matter_id?: string | null
          name?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "documents_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_current_version_id_fkey"
            columns: ["current_version_id"]
            isOneToOne: false
            referencedRelation: "document_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      firm_counters: {
        Row: {
          firm_id: string
          kind: string
          value: number
          year: number
        }
        Insert: {
          firm_id: string
          kind: string
          value?: number
          year: number
        }
        Update: {
          firm_id?: string
          kind?: string
          value?: number
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "firm_counters_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "firm_counters_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      firm_members: {
        Row: {
          firm_id: string
          role: Database["public"]["Enums"]["firm_role"]
          user_id: string
        }
        Insert: {
          firm_id: string
          role: Database["public"]["Enums"]["firm_role"]
          user_id: string
        }
        Update: {
          firm_id?: string
          role?: Database["public"]["Enums"]["firm_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "firm_members_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "firm_members_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "firm_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      firms: {
        Row: {
          brand: Json
          created_at: string
          custom_domain: string | null
          default_currency: Database["public"]["Enums"]["currency"]
          id: string
          legal_name: string | null
          name: string
          paystack_subaccount: string | null
          policies: Json
          rc_number: string | null
          reference_prefix: string
          slug: string
          stripe_account: string | null
          timezone: string
          vat_rate: number
        }
        Insert: {
          brand?: Json
          created_at?: string
          custom_domain?: string | null
          default_currency?: Database["public"]["Enums"]["currency"]
          id?: string
          legal_name?: string | null
          name: string
          paystack_subaccount?: string | null
          policies?: Json
          rc_number?: string | null
          reference_prefix?: string
          slug: string
          stripe_account?: string | null
          timezone?: string
          vat_rate?: number
        }
        Update: {
          brand?: Json
          created_at?: string
          custom_domain?: string | null
          default_currency?: Database["public"]["Enums"]["currency"]
          id?: string
          legal_name?: string | null
          name?: string
          paystack_subaccount?: string | null
          policies?: Json
          rc_number?: string | null
          reference_prefix?: string
          slug?: string
          stripe_account?: string | null
          timezone?: string
          vat_rate?: number
        }
        Relationships: []
      }
      intake_forms: {
        Row: {
          firm_id: string
          id: string
          is_active: boolean
          name: string | null
          schema: Json
          service_id: string | null
        }
        Insert: {
          firm_id: string
          id?: string
          is_active?: boolean
          name?: string | null
          schema: Json
          service_id?: string | null
        }
        Update: {
          firm_id?: string
          id?: string
          is_active?: boolean
          name?: string | null
          schema?: Json
          service_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "intake_forms_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_forms_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_forms_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      intake_responses: {
        Row: {
          answers: Json
          appointment_id: string | null
          client_id: string
          created_at: string
          firm_id: string
          form_id: string | null
          id: string
        }
        Insert: {
          answers: Json
          appointment_id?: string | null
          client_id: string
          created_at?: string
          firm_id: string
          form_id?: string | null
          id?: string
        }
        Update: {
          answers?: Json
          appointment_id?: string | null
          client_id?: string
          created_at?: string
          firm_id?: string
          form_id?: string | null
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "intake_responses_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_responses_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_responses_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_responses_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_responses_form_id_fkey"
            columns: ["form_id"]
            isOneToOne: false
            referencedRelation: "intake_forms"
            referencedColumns: ["id"]
          },
        ]
      }
      invites: {
        Row: {
          accepted_by: string | null
          created_at: string
          created_by: string | null
          email: string | null
          expires_at: string
          firm_id: string
          id: string
          matter_id: string | null
          phone: string | null
          role: Database["public"]["Enums"]["party_role"]
          token: string
        }
        Insert: {
          accepted_by?: string | null
          created_at?: string
          created_by?: string | null
          email?: string | null
          expires_at?: string
          firm_id: string
          id?: string
          matter_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["party_role"]
          token?: string
        }
        Update: {
          accepted_by?: string | null
          created_at?: string
          created_by?: string | null
          email?: string | null
          expires_at?: string
          firm_id?: string
          id?: string
          matter_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["party_role"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invites_accepted_by_fkey"
            columns: ["accepted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
        ]
      }
      invoice_items: {
        Row: {
          description: string
          id: string
          invoice_id: string
          quantity: number
          unit_minor: number
        }
        Insert: {
          description: string
          id?: string
          invoice_id: string
          quantity?: number
          unit_minor: number
        }
        Update: {
          description?: string
          id?: string
          invoice_id?: string
          quantity?: number
          unit_minor?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoice_items_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_items_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "partner_attribution"
            referencedColumns: ["invoice_id"]
          },
        ]
      }
      invoices: {
        Row: {
          appointment_id: string | null
          client_id: string
          created_at: string
          currency: Database["public"]["Enums"]["currency"]
          due_at: string | null
          firm_id: string
          id: string
          issued_at: string | null
          matter_id: string | null
          number: string
          paid_minor: number
          status: Database["public"]["Enums"]["invoice_status"]
          subtotal_minor: number
          total_minor: number
          vat_minor: number
        }
        Insert: {
          appointment_id?: string | null
          client_id: string
          created_at?: string
          currency: Database["public"]["Enums"]["currency"]
          due_at?: string | null
          firm_id: string
          id?: string
          issued_at?: string | null
          matter_id?: string | null
          number: string
          paid_minor?: number
          status?: Database["public"]["Enums"]["invoice_status"]
          subtotal_minor: number
          total_minor: number
          vat_minor?: number
        }
        Update: {
          appointment_id?: string | null
          client_id?: string
          created_at?: string
          currency?: Database["public"]["Enums"]["currency"]
          due_at?: string | null
          firm_id?: string
          id?: string
          issued_at?: string | null
          matter_id?: string | null
          number?: string
          paid_minor?: number
          status?: Database["public"]["Enums"]["invoice_status"]
          subtotal_minor?: number
          total_minor?: number
          vat_minor?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoices_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
        ]
      }
      lawyer_profiles: {
        Row: {
          bio: string | null
          category: string | null
          firm_id: string
          is_public: boolean
          photo_path: string | null
          practice_areas: string[]
          slug: string | null
          title: string | null
          user_id: string
        }
        Insert: {
          bio?: string | null
          category?: string | null
          firm_id: string
          is_public?: boolean
          photo_path?: string | null
          practice_areas?: string[]
          slug?: string | null
          title?: string | null
          user_id: string
        }
        Update: {
          bio?: string | null
          category?: string | null
          firm_id?: string
          is_public?: boolean
          photo_path?: string | null
          practice_areas?: string[]
          slug?: string | null
          title?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lawyer_profiles_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lawyer_profiles_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lawyer_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matter_lawyers: {
        Row: {
          firm_id: string
          is_lead: boolean
          matter_id: string
          user_id: string
        }
        Insert: {
          firm_id: string
          is_lead?: boolean
          matter_id: string
          user_id: string
        }
        Update: {
          firm_id?: string
          is_lead?: boolean
          matter_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "matter_lawyers_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_lawyers_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_lawyers_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_lawyers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matter_parties: {
        Row: {
          can_pay: boolean
          can_view_docs: boolean
          firm_id: string
          invited_by: string | null
          matter_id: string
          role: Database["public"]["Enums"]["party_role"]
          user_id: string
        }
        Insert: {
          can_pay?: boolean
          can_view_docs?: boolean
          firm_id: string
          invited_by?: string | null
          matter_id: string
          role: Database["public"]["Enums"]["party_role"]
          user_id: string
        }
        Update: {
          can_pay?: boolean
          can_view_docs?: boolean
          firm_id?: string
          invited_by?: string | null
          matter_id?: string
          role?: Database["public"]["Enums"]["party_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "matter_parties_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_parties_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_parties_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_parties_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_parties_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matter_statuses: {
        Row: {
          colour: string | null
          firm_id: string
          id: string
          is_terminal: boolean
          key: string
          label: string
          sort: number
        }
        Insert: {
          colour?: string | null
          firm_id: string
          id?: string
          is_terminal?: boolean
          key: string
          label: string
          sort?: number
        }
        Update: {
          colour?: string | null
          firm_id?: string
          id?: string
          is_terminal?: boolean
          key?: string
          label?: string
          sort?: number
        }
        Relationships: [
          {
            foreignKeyName: "matter_statuses_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matter_statuses_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      matters: {
        Row: {
          closed_at: string | null
          court_name: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          description: string | null
          firm_id: string
          handling_lawyer_id: string | null
          id: string
          judge: string | null
          next_action: string | null
          next_event_at: string | null
          next_event_note: string | null
          opened_at: string
          opposing_party: string | null
          originating_lawyer_id: string | null
          reference: string
          status_id: string | null
          suit_number: string | null
          title: string
          type: Database["public"]["Enums"]["matter_type"]
        }
        Insert: {
          closed_at?: string | null
          court_name?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          description?: string | null
          firm_id: string
          handling_lawyer_id?: string | null
          id?: string
          judge?: string | null
          next_action?: string | null
          next_event_at?: string | null
          next_event_note?: string | null
          opened_at?: string
          opposing_party?: string | null
          originating_lawyer_id?: string | null
          reference: string
          status_id?: string | null
          suit_number?: string | null
          title: string
          type: Database["public"]["Enums"]["matter_type"]
        }
        Update: {
          closed_at?: string | null
          court_name?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          description?: string | null
          firm_id?: string
          handling_lawyer_id?: string | null
          id?: string
          judge?: string | null
          next_action?: string | null
          next_event_at?: string | null
          next_event_note?: string | null
          opened_at?: string
          opposing_party?: string | null
          originating_lawyer_id?: string | null
          reference?: string
          status_id?: string | null
          suit_number?: string | null
          title?: string
          type?: Database["public"]["Enums"]["matter_type"]
        }
        Relationships: [
          {
            foreignKeyName: "matters_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matters_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matters_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matters_handling_lawyer_id_fkey"
            columns: ["handling_lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matters_originating_lawyer_id_fkey"
            columns: ["originating_lawyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matters_status_id_fkey"
            columns: ["status_id"]
            isOneToOne: false
            referencedRelation: "matter_statuses"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          appointment_id: string | null
          attachments: Json
          body: string | null
          created_at: string
          firm_id: string
          id: string
          matter_id: string | null
          read_at: string | null
          sender_id: string | null
        }
        Insert: {
          appointment_id?: string | null
          attachments?: Json
          body?: string | null
          created_at?: string
          firm_id: string
          id?: string
          matter_id?: string | null
          read_at?: string | null
          sender_id?: string | null
        }
        Update: {
          appointment_id?: string | null
          attachments?: Json
          body?: string | null
          created_at?: string
          firm_id?: string
          id?: string
          matter_id?: string | null
          read_at?: string | null
          sender_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_preferences: {
        Row: {
          channel: Database["public"]["Enums"]["channel"]
          enabled: boolean
          event: string
          user_id: string
        }
        Insert: {
          channel: Database["public"]["Enums"]["channel"]
          enabled?: boolean
          event: string
          user_id: string
        }
        Update: {
          channel?: Database["public"]["Enums"]["channel"]
          enabled?: boolean
          event?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          channel: Database["public"]["Enums"]["channel"]
          created_at: string
          error: string | null
          event: string
          firm_id: string | null
          id: string
          payload: Json
          read_at: string | null
          send_after: string
          sent_at: string | null
          status: string
          user_id: string
        }
        Insert: {
          channel: Database["public"]["Enums"]["channel"]
          created_at?: string
          error?: string | null
          event: string
          firm_id?: string | null
          id?: string
          payload?: Json
          read_at?: string | null
          send_after?: string
          sent_at?: string | null
          status?: string
          user_id: string
        }
        Update: {
          channel?: Database["public"]["Enums"]["channel"]
          created_at?: string
          error?: string | null
          event?: string
          firm_id?: string | null
          id?: string
          payload?: Json
          read_at?: string | null
          send_after?: string
          sent_at?: string | null
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount_minor: number
          currency: Database["public"]["Enums"]["currency"]
          id: string
          invoice_id: string
          paid_at: string | null
          provider: string
          provider_ref: string
          raw: Json | null
          status: Database["public"]["Enums"]["payment_status"]
        }
        Insert: {
          amount_minor: number
          currency: Database["public"]["Enums"]["currency"]
          id?: string
          invoice_id: string
          paid_at?: string | null
          provider: string
          provider_ref: string
          raw?: Json | null
          status?: Database["public"]["Enums"]["payment_status"]
        }
        Update: {
          amount_minor?: number
          currency?: Database["public"]["Enums"]["currency"]
          id?: string
          invoice_id?: string
          paid_at?: string | null
          provider?: string
          provider_ref?: string
          raw?: Json | null
          status?: Database["public"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "payments_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "partner_attribution"
            referencedColumns: ["invoice_id"]
          },
        ]
      }
      profiles: {
        Row: {
          address: string | null
          client_type: Database["public"]["Enums"]["client_type"] | null
          company_name: string | null
          country: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          locale: string
          phone: string | null
          preferred_channel: Database["public"]["Enums"]["channel"]
          state: string | null
          timezone: string
        }
        Insert: {
          address?: string | null
          client_type?: Database["public"]["Enums"]["client_type"] | null
          company_name?: string | null
          country?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          locale?: string
          phone?: string | null
          preferred_channel?: Database["public"]["Enums"]["channel"]
          state?: string | null
          timezone?: string
        }
        Update: {
          address?: string | null
          client_type?: Database["public"]["Enums"]["client_type"] | null
          company_name?: string | null
          country?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          locale?: string
          phone?: string | null
          preferred_channel?: Database["public"]["Enums"]["channel"]
          state?: string | null
          timezone?: string
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          created_at: string
          endpoint: string
          id: string
          keys: Json
          user_agent: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          endpoint: string
          id?: string
          keys: Json
          user_agent?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          endpoint?: string
          id?: string
          keys?: Json
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      services: {
        Row: {
          currency: Database["public"]["Enums"]["currency"]
          description: string | null
          duration_min: number
          firm_id: string
          id: string
          is_active: boolean
          lawyer_category: string | null
          name: string
          price_minor: number
          requires_prepayment: boolean
          slug: string
          sort: number
          virtual_available: boolean
        }
        Insert: {
          currency?: Database["public"]["Enums"]["currency"]
          description?: string | null
          duration_min: number
          firm_id: string
          id?: string
          is_active?: boolean
          lawyer_category?: string | null
          name: string
          price_minor: number
          requires_prepayment?: boolean
          slug: string
          sort?: number
          virtual_available?: boolean
        }
        Update: {
          currency?: Database["public"]["Enums"]["currency"]
          description?: string | null
          duration_min?: number
          firm_id?: string
          id?: string
          is_active?: boolean
          lawyer_category?: string | null
          name?: string
          price_minor?: number
          requires_prepayment?: boolean
          slug?: string
          sort?: number
          virtual_available?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "services_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "services_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assignee_id: string | null
          created_at: string
          due_at: string | null
          firm_id: string
          id: string
          matter_id: string | null
          status: string
          title: string
        }
        Insert: {
          assignee_id?: string | null
          created_at?: string
          due_at?: string | null
          firm_id: string
          id?: string
          matter_id?: string | null
          status?: string
          title: string
        }
        Update: {
          assignee_id?: string | null
          created_at?: string
          due_at?: string | null
          firm_id?: string
          id?: string
          matter_id?: string | null
          status?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
        ]
      }
      updates: {
        Row: {
          body: string | null
          created_at: string
          firm_id: string
          id: string
          kind: Database["public"]["Enums"]["update_kind"]
          matter_id: string
          occurred_at: string
          payload: Json
          posted_by: string | null
          title: string
          visibility: Database["public"]["Enums"]["visibility"]
        }
        Insert: {
          body?: string | null
          created_at?: string
          firm_id: string
          id?: string
          kind: Database["public"]["Enums"]["update_kind"]
          matter_id: string
          occurred_at?: string
          payload?: Json
          posted_by?: string | null
          title: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Update: {
          body?: string | null
          created_at?: string
          firm_id?: string
          id?: string
          kind?: Database["public"]["Enums"]["update_kind"]
          matter_id?: string
          occurred_at?: string
          payload?: Json
          posted_by?: string | null
          title?: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Relationships: [
          {
            foreignKeyName: "updates_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "updates_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "updates_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "updates_posted_by_fkey"
            columns: ["posted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      firm_public: {
        Row: {
          brand: Json | null
          custom_domain: string | null
          default_currency: Database["public"]["Enums"]["currency"] | null
          id: string | null
          name: string | null
          policies: Json | null
          slug: string | null
          timezone: string | null
        }
        Insert: {
          brand?: Json | null
          custom_domain?: string | null
          default_currency?: Database["public"]["Enums"]["currency"] | null
          id?: string | null
          name?: string | null
          policies?: Json | null
          slug?: string | null
          timezone?: string | null
        }
        Update: {
          brand?: Json | null
          custom_domain?: string | null
          default_currency?: Database["public"]["Enums"]["currency"] | null
          id?: string | null
          name?: string | null
          policies?: Json | null
          slug?: string | null
          timezone?: string | null
        }
        Relationships: []
      }
      partner_attribution: {
        Row: {
          amount_minor: number | null
          appointment_id: string | null
          currency: Database["public"]["Enums"]["currency"] | null
          firm_id: string | null
          handling_lawyer_id: string | null
          invoice_id: string | null
          invoice_number: string | null
          matter_id: string | null
          originating_lawyer_id: string | null
          paid_at: string | null
          payment_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invoices_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firm_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_firm_id_fkey"
            columns: ["firm_id"]
            isOneToOne: false
            referencedRelation: "firms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_matter_id_fkey"
            columns: ["matter_id"]
            isOneToOne: false
            referencedRelation: "matters"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      accept_invite: { Args: { p_token: string }; Returns: Json }
      admin_w: { Args: { f: string }; Returns: boolean }
      audit: {
        Args: {
          p_action: string
          p_entity: string
          p_entity_id: string
          p_firm: string
          p_meta?: Json
        }
        Returns: undefined
      }
      available_slots: {
        Args: {
          p_date: string
          p_firm: string
          p_lawyer: string
          p_service: string
        }
        Returns: {
          ends_at: string
          starts_at: string
        }[]
      }
      book_appointment: {
        Args: {
          p_client_timezone?: string
          p_firm: string
          p_intake?: Json
          p_intake_form?: string
          p_lawyer: string
          p_mode?: Database["public"]["Enums"]["appointment_mode"]
          p_service: string
          p_starts_at: string
        }
        Returns: Json
      }
      can_access_document: { Args: { d: string }; Returns: boolean }
      can_access_invoice: { Args: { i: string }; Returns: boolean }
      can_see_profile: { Args: { p: string }; Returns: boolean }
      cancel_appointment: {
        Args: { p_appointment: string; p_reason?: string }
        Returns: undefined
      }
      digest_sittings_without_update: { Args: never; Returns: number }
      enqueue_appointment_reminders: { Args: never; Returns: number }
      enqueue_court_reminders: { Args: never; Returns: number }
      enqueue_notification: {
        Args: {
          p_event: string
          p_firm: string
          p_payload: Json
          p_send_after?: string
          p_user: string
        }
        Returns: undefined
      }
      has_firm_role: {
        Args: { f: string; roles: Database["public"]["Enums"]["firm_role"][] }
        Returns: boolean
      }
      is_appointment_client: { Args: { a: string }; Returns: boolean }
      is_client_of_firm: { Args: { f: string }; Returns: boolean }
      is_firm_member: { Args: { f: string }; Returns: boolean }
      is_matter_party: { Args: { m: string }; Returns: boolean }
      mark_overdue_invoices: { Args: never; Returns: number }
      mfa_ok: { Args: never; Returns: boolean }
      next_reference: {
        Args: { p_firm: string; p_kind: string }
        Returns: string
      }
      post_court_update: {
        Args: {
          p_adjourned_at_instance_of?: string
          p_court_name?: string
          p_internal_note?: string
          p_matter: string
          p_next_date?: string
          p_next_purpose?: string
          p_note_to_client?: string
          p_occurred_at?: string
          p_outcome: string
        }
        Returns: string
      }
      record_payment: {
        Args: {
          p_amount_minor: number
          p_currency: Database["public"]["Enums"]["currency"]
          p_invoice_number: string
          p_provider: string
          p_provider_ref: string
          p_raw?: Json
          p_status: Database["public"]["Enums"]["payment_status"]
        }
        Returns: Json
      }
      release_expired_holds: { Args: never; Returns: number }
      save_consultation_notes: {
        Args: {
          p_advice_given?: string
          p_appointment: string
          p_client_summary: string
          p_follow_up?: string
          p_internal_notes?: string
          p_mark_completed?: boolean
        }
        Returns: string
      }
      staff_w: { Args: { f: string }; Returns: boolean }
    }
    Enums: {
      appointment_mode: "virtual" | "in_person" | "phone"
      appointment_status:
        | "pending"
        | "awaiting_payment"
        | "confirmed"
        | "rescheduled"
        | "completed"
        | "cancelled"
        | "no_show"
      channel: "in_app" | "push" | "email" | "sms" | "whatsapp"
      client_type: "individual" | "business"
      consent_kind:
        | "terms"
        | "privacy"
        | "engagement"
        | "recording"
        | "marketing"
      content_kind: "page" | "faq" | "article" | "announcement" | "testimonial"
      currency: "NGN" | "USD"
      firm_role: "owner" | "admin" | "lawyer" | "staff"
      invoice_status:
        | "draft"
        | "issued"
        | "partially_paid"
        | "paid"
        | "overdue"
        | "cancelled"
      matter_type:
        | "litigation"
        | "property"
        | "corporate"
        | "estate"
        | "family"
        | "employment"
        | "debt_recovery"
        | "ip"
        | "regulatory"
        | "immigration"
        | "advisory"
        | "other"
      party_role: "client" | "contact" | "co_counsel"
      payment_status: "initiated" | "succeeded" | "failed" | "refunded"
      update_kind:
        | "court_sitting"
        | "consultation"
        | "appointment"
        | "filing"
        | "correspondence"
        | "milestone"
        | "fee"
        | "document"
        | "note"
        | "status_change"
      visibility: "client" | "internal"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      appointment_mode: ["virtual", "in_person", "phone"],
      appointment_status: [
        "pending",
        "awaiting_payment",
        "confirmed",
        "rescheduled",
        "completed",
        "cancelled",
        "no_show",
      ],
      channel: ["in_app", "push", "email", "sms", "whatsapp"],
      client_type: ["individual", "business"],
      consent_kind: [
        "terms",
        "privacy",
        "engagement",
        "recording",
        "marketing",
      ],
      content_kind: ["page", "faq", "article", "announcement", "testimonial"],
      currency: ["NGN", "USD"],
      firm_role: ["owner", "admin", "lawyer", "staff"],
      invoice_status: [
        "draft",
        "issued",
        "partially_paid",
        "paid",
        "overdue",
        "cancelled",
      ],
      matter_type: [
        "litigation",
        "property",
        "corporate",
        "estate",
        "family",
        "employment",
        "debt_recovery",
        "ip",
        "regulatory",
        "immigration",
        "advisory",
        "other",
      ],
      party_role: ["client", "contact", "co_counsel"],
      payment_status: ["initiated", "succeeded", "failed", "refunded"],
      update_kind: [
        "court_sitting",
        "consultation",
        "appointment",
        "filing",
        "correspondence",
        "milestone",
        "fee",
        "document",
        "note",
        "status_change",
      ],
      visibility: ["client", "internal"],
    },
  },
} as const
