// Server-rendered PDF invoice / receipt (no third-party renderer).
// Reads with the caller's own session, so RLS decides whether they may see it.

import { supabaseServer } from "@/lib/supabase/server";
import { firmById } from "@/lib/tenant";
import { formatMoneyPlain } from "@/lib/money";
import { textPdf, PdfEncodingError, type PdfLine } from "@/lib/pdf";
import { formatDay } from "@/lib/days";

export async function GET(_request: Request, ctx: { params: Promise<{ invoice: string }> }) {
  const { invoice: id } = await ctx.params;
  const supabase = await supabaseServer();
  if (!supabase) return new Response("Not configured", { status: 503 });
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const { data } = await supabase
    .from("invoices")
    .select("id, firm_id, number, status, currency, subtotal_minor, vat_minor, total_minor, paid_minor, issued_at, due_at, client_id")
    .eq("id", id)
    .maybeSingle();
  const inv = data as {
    id: string; firm_id: string; number: string; status: string; currency: string;
    subtotal_minor: number; vat_minor: number; total_minor: number; paid_minor: number;
    issued_at: string | null; due_at: string | null; client_id: string;
  } | null;
  if (!inv) return new Response("Not found", { status: 404 });

  const [{ data: items }, { data: payments }, { data: profile }, firm] = await Promise.all([
    supabase.from("invoice_items").select("description, quantity, unit_minor").eq("invoice_id", inv.id),
    supabase.from("payments").select("provider, provider_ref, status, amount_minor, paid_at").eq("invoice_id", inv.id),
    supabase.from("profiles").select("full_name, email, phone").eq("id", inv.client_id).maybeSingle(),
    firmById(inv.firm_id),
  ]);
  const itemRows = (items ?? []) as { description: string; quantity: number; unit_minor: number }[];
  const payRows = (payments ?? []) as { provider: string; provider_ref: string; status: string; amount_minor: number; paid_at: string | null }[];
  const client = profile as { full_name: string | null; email: string | null; phone: string | null } | null;
  const money = (m: number) => formatMoneyPlain(m, inv.currency);
  const date = (iso: string | null) => (iso ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeZone: firm?.timezone ?? "Africa/Lagos" }).format(new Date(iso)) : "-");
  // invoices.due_at is a DATE — a calendar day, never an instant a timezone may move to the day
  // before. issued_at and paid_at are instants and are rendered in the firm's zone above.
  const day = (ymd: string | null) => (ymd ? formatDay(ymd) : "-");
  const contact = firm?.brand.contact ?? {};

  const lines: PdfLine[] = [
    { text: firm?.legal_name ?? firm?.name ?? "Docket", size: 18, bold: true },
    ...(contact.address ? [{ text: contact.address, size: 10 }] : []),
    ...(contact.email ? [{ text: contact.email, size: 10 }] : []),
    ...(contact.phone ? [{ text: contact.phone, size: 10, gap: 8 }] : [{ text: "", gap: 8 }]),
    { text: `${inv.status === "paid" ? "RECEIPT" : "INVOICE"} ${inv.number}`, size: 14, bold: true },
    { text: `Status: ${inv.status.replace("_", " ")}`, size: 10 },
    { text: `Issued: ${date(inv.issued_at)}`, size: 10 },
    ...(inv.due_at ? [{ text: `Due: ${day(inv.due_at)}`, size: 10 }] : []),
    { text: "", gap: 6 },
    { text: "Billed to", size: 11, bold: true },
    { text: client?.full_name ?? client?.email ?? client?.phone ?? "Client", size: 10 },
    ...(client?.email ? [{ text: client.email, size: 10 }] : []),
    ...(client?.phone ? [{ text: client.phone, size: 10 }] : []),
    { text: "", gap: 6 },
    { text: "Items", size: 11, bold: true },
    ...itemRows.map((it) => ({
      text: `${it.description}${Number(it.quantity) !== 1 ? ` x ${it.quantity}` : ""}    ${money(Math.round(it.unit_minor * Number(it.quantity)))}`,
      size: 10,
    })),
    { text: "", gap: 4 },
    { text: `Subtotal    ${money(inv.subtotal_minor)}`, size: 10 },
    { text: `VAT         ${money(inv.vat_minor)}`, size: 10 },
    { text: `Total       ${money(inv.total_minor)}`, size: 11, bold: true },
    { text: `Paid        ${money(inv.paid_minor)}`, size: 10, gap: 8 },
    { text: "Payments", size: 11, bold: true },
    ...(payRows.length === 0
      ? [{ text: "No payments recorded yet.", size: 10 }]
      : payRows.map((p) => ({ text: `${date(p.paid_at)}  ${p.provider} ${p.provider_ref}  ${money(p.amount_minor)}  ${p.status}`, size: 10 }))),
    { text: "", gap: 12 },
    { text: "Generated by Docket. Amounts settle directly to the firm.", size: 8 },
  ];

  // textPdf refuses text the standard fonts cannot draw rather than printing "?" where a name was
  // (src/lib/pdf.ts). That refusal names the characters, and it reaches the reader as the sentence
  // it is: a firm whose legal name or a lawyer whose line item carries a dot-below vowel or the
  // naira sign was otherwise handing its client a bare 500.
  let bytes: ReturnType<typeof textPdf>;
  try {
    bytes = textPdf(lines);
  } catch (e) {
    if (e instanceof PdfEncodingError) {
      return new Response(`${e.message}\n\nThe invoice itself is unaffected; ask the firm to respell the value, or read it at /app/payments/${inv.id}.\n`,
        { status: 422, headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "private, no-store" } });
    }
    throw e;
  }
  return new Response(bytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${inv.number}.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}
